### ISSUE TITLE
Approximate API calls needed

### ISSUE THREAD

**Issue by preethamnagesh8** [stevespringett/vulndb-data-mirror#2]
Hi Steve,
    I am working on dependency track and am trying to integrate with Vuln DB. According to the documentation here - [https://docs.dependencytrack.org/datasources/vulndb/](url) I see that 2 things happen:

1. Vuln DB Data is completely mirrored to vulndb directory - performed by 'vulndb-data-mirror' tool.
2. Dependency track automatically syncs Vuln DB data every 24 hrs.

I read in the documentation of the tool:
`You may estimate the number of requests required by dividing 100 by the total number of results in each of the three feeds.`
I don't quite understand the meaning of three feeds. What are you referring to here ?

I would like to understand how many API calls will be made by 'vulndb-data-mirror' tool for step 1 and how many API calls would be made for step 2.

**Comment by stevespringett** [comment]
Refer to the VulnDB API documentation. They support a vendors api, products api, and a vulnerability api. Three feeds.

If there are 180K vulnerabilities in their database and their API paginates every 100 records, then you'll need to make 1800 request in order to mirror the vulnerabilities. Depending on your subscription model, the number of requests you make may be a limitation of your usage, therefore you need to calculate how many requests are needed and what your VulnDB license permits.

**Comment by preethamnagesh8** [comment]
Thanks for the info Steve. Will look into that.
